- name: "주일 1부 예배"
  day: "주일"
  time: "09:00"
  location: "본당"
  language: "한국어"

- name: "주일 2부 예배"
  day: "주일"
  time: "11:00"
  location: "본당"
  language: "한국어"

- name: "Youth Service"
  day: "주일"
  time: "11:00"
  location: "별관"
  language: "한국어/영어"

- name: "수요 기도회"
  day: "수요일"
  time: "19:30"
  location: "본당"
  language: "한국어"

- name: "새벽 기도회"
  day: "화-토"
  time: "06:00"
  location: "본당"
  language: "한국어"
